runtime: nodejs16

instance_class: F2

env_variables:
  PORT: 8000
  MONGO_URI: mongodb+srv://ayerinmattxc:g3YR6DvjayVOECYS@violationtracker.fpqujlc.mongodb.net/?retryWrites=true&w=majority

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto